[build]
builder = "RAILPACK"
buildCommand = "cd backend && npm install"

[deploy]
startCommand = "cd backend && node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
